id = "tsar"
name = "Argent"
version = "0.1.0"
schema_version = 1
authors = ["x <x032205@gmail.com>"]
description = "Minimal and modern semi-transparent dark theme, in desaturated silver and the original saturated palette."
repository = "https://github.com/x032205/argent-zed-theme"
